### ISSUE TITLE
Wrong date format

### ISSUE THREAD

**Issue by Briesmi** [DrGER2/MMI3G-Navdb-Unblocker#3]
Could you pls adjust the date format  for $(date) and maybe setup a locale like 'LC_TIME="de_DE.UTF-8"  date' ?
For now the output is 'Thu Jan 01 00:02:58 UTC 1970' .

I know, it's not important but it looks a lil' bit more nice.

Thanks.

**Comment by DrGER2** [comment]
If QNX date(1) returned the actual date, this would make sense, but it does not.  Rather, it returns the time since the system started relative to the Unix epoch (1970-01-01 UTC).  Binary getTime returns the "real" time (as understood by the MMI system); I don't know if getTime is affected by LC_TIME; I doubt that it is.

**Comment by Briesmi** [comment]
Thank you! I just ignored the $(date) output since its not needed. 

Thanks for your great work.
